# pandas.errors.UnsupportedFunctionCall

> 原文：[`pandas.pydata.org/docs/reference/api/pandas.errors.UnsupportedFunctionCall.html`](https://pandas.pydata.org/docs/reference/api/pandas.errors.UnsupportedFunctionCall.html)

```py
exception pandas.errors.UnsupportedFunctionCall
```

尝试调用不支持的 numpy 函数时引发异常。

例如，`np.cumsum(groupby_object)`。

Examples

```py
>>> df = pd.DataFrame({"A": [0, 0, 1, 1],
...                    "B": ["x", "x", "z", "y"],
...                    "C": [1, 2, 3, 4]}
...                   )
>>> np.cumsum(df.groupby(["A"]))
Traceback (most recent call last):
UnsupportedFunctionCall: numpy operations are not valid with groupby.
Use .groupby(...).cumsum() instead 
```
