# pandas.errors.SettingWithCopyError

> 原文：[`pandas.pydata.org/docs/reference/api/pandas.errors.SettingWithCopyError.html`](https://pandas.pydata.org/docs/reference/api/pandas.errors.SettingWithCopyError.html)

```py
exception pandas.errors.SettingWithCopyError
```

尝试在从`DataFrame`复制的切片上设置时引发异常。

`mode.chained_assignment`需要设置为‘raise’。这可能会在链式索引时无意中发生。

有关评估顺序的更多信息，请参阅用户指南。

有关视图与复制的更多信息，请参阅用户指南。

示例

```py
>>> pd.options.mode.chained_assignment = 'raise'
>>> df = pd.DataFrame({'A': [1, 1, 1, 2, 2]}, columns=['A'])
>>> df.loc[0:3]['A'] = 'a' 
... # SettingWithCopyError: A value is trying to be set on a copy of a... 
```
