# pandas.errors.OutOfBoundsDatetime

> 原文：[`pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html`](https://pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html)

```py
exception pandas.errors.OutOfBoundsDatetime
```

当日期时间超出可表示范围时引发。

示例

```py
>>> pd.to_datetime("08335394550")
Traceback (most recent call last):
OutOfBoundsDatetime: Parsing "08335394550" to datetime overflows,
at position 0 
```
