# pandas.errors.ChainedAssignmentError

> 原文：[`pandas.pydata.org/docs/reference/api/pandas.errors.ChainedAssignmentError.html`](https://pandas.pydata.org/docs/reference/api/pandas.errors.ChainedAssignmentError.html)

```py
exception pandas.errors.ChainedAssignmentError
```

警告：尝试使用链式赋值时引发的警告。

当启用`mode.copy_on_write`选项时，链式赋值永远不起作用。在这种情况下，我们总是在设置一个临时对象，该对象是索引操作（getitem）的结果，而在写时复制下，始终表现为副本。因此，通过链式赋值永远无法更新原始的 Series 或 DataFrame。

欲了解视图与副本的更多信息，请参阅用户指南。

示例

```py
>>> pd.options.mode.copy_on_write = True
>>> df = pd.DataFrame({'A': [1, 1, 1, 2, 2]}, columns=['A'])
>>> df["A"][0:3] = 10 
... # ChainedAssignmentError: ...
>>> pd.options.mode.copy_on_write = False 
```
