- en: scipy.io.FortranFormattingError
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: scipy.io.FortranFormattingError
- en: Original text：[https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.io.FortranFormattingError.html#scipy.io.FortranFormattingError](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.io.FortranFormattingError.html#scipy.io.FortranFormattingError)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.io.FortranFormattingError.html#scipy.io.FortranFormattingError](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.io.FortranFormattingError.html#scipy.io.FortranFormattingError)
- en: '[PRE0]'
  id: totrans-2
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: Indicates that the file ended mid-record.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 表明文件在记录中途结束。
- en: Descends from TypeError for backward compatibility.
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 派生自TypeError以保持向后兼容性。
- en: '[PRE1]'
  id: totrans-5
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: POSIX exception code
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: POSIX异常代码
- en: '[PRE2]'
  id: totrans-7
  prefs: []
  type: TYPE_PRE
  zh: '[PRE2]'
- en: exception filename
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 异常 filename
- en: '[PRE3]'
  id: totrans-9
  prefs: []
  type: TYPE_PRE
  zh: '[PRE3]'
- en: second exception filename
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 第二个异常 filename
- en: '[PRE4]'
  id: totrans-11
  prefs: []
  type: TYPE_PRE
  zh: '[PRE4]'
- en: exception strerror
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 异常 strerror
- en: '[PRE5]'
  id: totrans-13
  prefs: []
  type: TYPE_PRE
  zh: '[PRE5]'
- en: Exception.with_traceback(tb) – set self.__traceback__ to tb and return self.
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: Exception.with_traceback(tb) – 设置self.__traceback__为tb并返回self。
