# scipy.io.wavfile.WavFileWarning

> 原文：[https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.io.wavfile.WavFileWarning.html#scipy.io.wavfile.WavFileWarning](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.io.wavfile.WavFileWarning.html#scipy.io.wavfile.WavFileWarning)

```py
exception scipy.io.wavfile.WavFileWarning
```

```py
with_traceback()
```

Exception.with_traceback(tb) – 设置 self.__traceback__ 为 tb 并返回 self。
