# `scipy.integrate.ODEintWarning`

> 原文：[`docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.integrate.ODEintWarning.html#scipy.integrate.ODEintWarning`](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.integrate.ODEintWarning.html#scipy.integrate.ODEintWarning)

```py
exception scipy.integrate.ODEintWarning
```

在执行[`odeint`](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.integrate.ODEintWarning.html#scipy.integrate.ODEintWarning "scipy.integrate.odeint")时引发警告。

```py
with_traceback()
```

`Exception.with_traceback(tb)` – 将 self.__traceback__ 设置为 tb 并返回 self。
