# numpy.exceptions.AxisError

> 原文：[`numpy.org/doc/1.26/reference/generated/numpy.exceptions.AxisError.html`](https://numpy.org/doc/1.26/reference/generated/numpy.exceptions.AxisError.html)

```py
exception exceptions.AxisError(axis, ndim=None, msg_prefix=None)
```

提供的轴无效。

当指定了大于数组维度数量的 `axis` 参数时，会引发此异常。为了与针对较旧的 numpy 版本编写的代码兼容，该版本对此情况使用了 *ValueError* 和 *IndexError* 的混合方式进行引发异常，此异常子类化了这两种异常，以确保 `except ValueError` 和 `except IndexError` 语句仍然可以捕获到 `AxisError`。

版本 1.13 中新增。

参数：

**axis**int 或 str

超出范围的轴或自定义异常消息。如果提供了一个轴，则也应该指定`ndim`。

**ndim**int，可选

数组维度的数量。

**msg_prefix**str，可选

异常消息的前缀。

示例

```py
>>> array_1d = np.arange(10)
>>> np.cumsum(array_1d, axis=1)
Traceback (most recent call last):
  ...
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1 
```

负轴被保留：

```py
>>> np.cumsum(array_1d, axis=-2)
Traceback (most recent call last):
  ...
numpy.exceptions.AxisError: axis -2 is out of bounds for array of dimension 1 
```

类构造函数通常以轴和数组维数为参数：

```py
>>> print(np.AxisError(2, 1, msg_prefix='error'))
error: axis 2 is out of bounds for array of dimension 1 
```

或者可以传递自定义异常消息：

```py
>>> print(np.AxisError('Custom error message'))
Custom error message 
```

属性：

**axis**int，可选

超出范围的轴或如果提供了自定义异常消息则为 `None`。这应该是用户传递的轴，在解析负索引之前的任何规范化。

版本 1.22 中新增。

**ndim**int，可选

数组维度的数量或如果提供了自定义异常消息则为 `None`。

版本 1.22 中新增。
