- en: pandas.errors.UnsupportedFunctionCall
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: pandas.errors.UnsupportedFunctionCall
- en: 原文：[https://pandas.pydata.org/docs/reference/api/pandas.errors.UnsupportedFunctionCall.html](https://pandas.pydata.org/docs/reference/api/pandas.errors.UnsupportedFunctionCall.html)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://pandas.pydata.org/docs/reference/api/pandas.errors.UnsupportedFunctionCall.html](https://pandas.pydata.org/docs/reference/api/pandas.errors.UnsupportedFunctionCall.html)
- en: '[PRE0]'
  id: totrans-2
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: Exception raised when attempting to call a unsupported numpy function.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 尝试调用不支持的 numpy 函数时引发异常。
- en: For example, `np.cumsum(groupby_object)`.
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 例如，`np.cumsum(groupby_object)`。
- en: Examples
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: Examples
- en: '[PRE1]'
  id: totrans-6
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
