- en: numpy.testing.assert_raises
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: numpy.testing.assert_raises
- en: 原文：[https://numpy.org/doc/1.26/reference/generated/numpy.testing.assert_raises.html](https://numpy.org/doc/1.26/reference/generated/numpy.testing.assert_raises.html)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://numpy.org/doc/1.26/reference/generated/numpy.testing.assert_raises.html](https://numpy.org/doc/1.26/reference/generated/numpy.testing.assert_raises.html)
- en: '[PRE0]'
  id: totrans-2
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: '[PRE1]'
  id: totrans-3
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: Fail unless an exception of class exception_class is thrown by callable when
    invoked with arguments args and keyword arguments kwargs. If a different type
    of exception is thrown, it will not be caught, and the test case will be deemed
    to have suffered an error, exactly as for an unexpected exception.
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 当使用参数args和关键字参数kwargs调用可调用对象时，如果抛出了exception_class类的异常，则失败。如果抛出了不同类型的异常，它不会被捕获，测试用例将被视为发生错误，就像发生了意外异常一样。
- en: 'Alternatively, [`assert_raises`](#numpy.testing.assert_raises "numpy.testing.assert_raises")
    can be used as a context manager:'
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: 或者，[`assert_raises`](#numpy.testing.assert_raises "numpy.testing.assert_raises")可以作为上下文管理器使用：
- en: '[PRE2]'
  id: totrans-6
  prefs: []
  type: TYPE_PRE
  zh: '[PRE2]'
- en: is equivalent to
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 等价于
- en: '[PRE3]'
  id: totrans-8
  prefs: []
  type: TYPE_PRE
  zh: '[PRE3]'
