- en: pandas.errors.OutOfBoundsDatetime
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: pandas.errors.OutOfBoundsDatetime
- en: 原文：[https://pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html](https://pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html](https://pandas.pydata.org/docs/reference/api/pandas.errors.OutOfBoundsDatetime.html)
- en: '[PRE0]'
  id: totrans-2
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: Raised when the datetime is outside the range that can be represented.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 当日期时间超出可表示范围时引发。
- en: Examples
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 示例
- en: '[PRE1]'
  id: totrans-5
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
